### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by geraldhansen** [supertommy/swift-status-bar-app-osx#3]
Hi,
I try to open and build this project with XCode Version 6.1.1 (6A2008a). But just if I push the build and run button I got some compile errors.
SwiftStatusBarApplication/AppDelegate.swift:13:5: 'IBOutlet' property has non-optional type 'NSWindow'
SwiftStatusBarApplication/AppDelegate.swift:25:45: 'Double' is not convertible to 'CGFloat'
SwiftStatusBarApplication/IconView.swift:43:1: 'required' initializer 'init(coder:)' must be provided by subclass of 'NSView'

I try to fix this with the recommendations of XCode, but this won't help. I am very new to Swift, XCode and Apple OSX development and did not see what I can do, but it would be very nice to get this project running for me for learning issues.

Thanks a lot

**Comment by supertommy** [comment]
I finally got around to noticing that there have been various pull requests on this project and have merged them so try to pull and compile it again. It ran on my Mac running Yosemite and Xcode 6.1.1
